/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/*
 * Class:     com_example_cog_ndktraiining_MainActivity
 * Method:    HelloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_cog_ndktraiining_MainActivity_HelloJNI
  (JNIEnv *env, jobject  obj){

  (*env)->NewStringUTF(env, "Hello this is from NDK");


  }
